### ISSUE TITLE
Dependancy problem in HDF5 plugin

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#10]
If two variables are written in HDF5 and that the select depends on both, there is a problem because they both need to be exposed before they can be exposed...

_e.g._
```yaml
outputs:
  iter:
    select: $iter>0 & $rank>0
  rank:
    select: $iter>0 & $rank>0
```
