### ISSUE TITLE
FlowVR yaml

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#101]
In GitLab by @ksiero on Sep 28, 2018, 13:45

```yaml
metadata:
  some_data_size: int

plugins:
  flowvr:
    component: module            # the only option for now
    status: status_flag          # status_flag = module::getStatus();
    wait: loop_flag              # when user exposes `loop_flag`, plugin calls: loop_flag = module::wait();
    abort_on: abort_event        # on this event plugin calls module::abort()
    input_ports:
      my_input_port:
        type: {type: array, subtype: double, size: $some_data_size}
        data: some_data_shr   # PDI_access will return a pointer to FlowVR shared memory
      my_event_port:          # no 'data' node means this gets only STAMP message
        event_port: true      # default: false
        stamps:
          global_it:
            type: int
            data: recv_it     # PDI_access (PDI_IN)
          global_time:
            type: float
            data: recv_time   # PDI_access (PDI_IN)
    output_ports:
      my_output_port:
        type: {type: array, subtype: int64, size: 1024}
        data: comp_array_shr  # PDI_access will allocate space in FlowVR shared memory with
                                # size of comp_array_shr and call module::put before wait
        stamps:
          my_int_stamp:
            type: int
            data: comp_it     # PDI_access (PDI_OUT)
          my_double_stamp:
            type: float
            data: comp_time   # PDI_access (PDI_OUT)
```

@jbigot could you look at this config? I cannot find Bruno nickname to notify him.
