### ISSUE TITLE
Datatypes comparing limitation

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#110]
In GitLab by @tpaluszk on Feb 21, 2019, 11:53

Currently in PDI there is no way to distinguish between datatypes that have the same parameters.  
For example, I'm currently implementing transtype features of mpi plugin (#107) and need to check the types of `mpi_comm` and `mpi_comm_f` and the only options I have is to assume that type of specific parameters is a `MPI_Comm` or to make the user specify the types of descriptors once more in mpi node.
Example config for mpi plugin transtype (with first option in mind):  
```yaml
data:
  mpi_comm: MPI_Comm
  mpi_comm_f: MPI_Comm_f  
plugins:
  mpi:
    transtype:
      mpi_comm: mpi_comm_f
```
