### ISSUE TITLE
Change logger configuration

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#128]
In GitLab by @tpaluszk on Apr 9, 2019, 12:56

Currently plugin-specific logging configuration expects a `logging` keyword in the plugin config, but some plugins might expect a list as top-level config, in which case logging config can't be specified.  
Possible solution is to move `logging` keyword from plugin to global `logging` keyword in pdi config.  
E.g.
```yaml
pdi:
  logging:
    level:
      global: off
      flowvr: debug
...
  plugins:
    flowvr:
      ...
```
