### ISSUE TITLE
support a hierarchy of names in the data store

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#134]
The data store currently offers a flat view: i.e. each "data" shared has a name in a flat namespace.

This makes sharing variable with encapsulation difficult, e.g. a C++ `std::list`.

It would be interesting to support a hierarchy of nested namespaces that can contain map and lists (json-style).

With a data description like that:
```YAML
metadata:
  my_list_size: int
data:
  my_list:
    type: list
    subtype: double
    size: $my_list_size
```

One could then share a list like that:

```C++
std::list<double> my_list;
//...
share("my_list_size", my_list.size());
int id = 0;
for ( auto list_elem: my_list) {
  share("my_list[%d]", list_elem, id);
  ++ id;
}
```
