### ISSUE TITLE
Order of Initial value for metadata

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#155]
In GitLab by @ksiero on Oct 10, 2019, 11:24

There is no way to set an order of loading data or metadata. This is a limitation in case user would want to initialize some metadata with reference. For example:
```yaml
metadata:
    length:
        type: int64
        init_value: 32
    width:
        type: int64
        init_value: $length * 2
```

We can easily fix this by letting user to define a metadata as an array:
```yaml
metadata:
    - length:
        type: int64
        init_value: 32
    - width:
        type: int64
        init_value: $length * 2
```
In this case we are sure that the loading order is correct.

@jbigot, @tpaluszk What do you think about it?
