### ISSUE TITLE
Support groups in HDF5

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#156]
In GitLab by @ksiero on Nov 6, 2019, 14:06

We can add groups support for HDF5. I will present my proposition below.

Old config:
```yml
decl_hdf5:
  file: data.h5
  datasets:
    data:
      type: array
      subtype: double
      size: [10, '$psize[0]*($dsize[0]-2)', '$psize[1]*($dsize[1]-2)']
  write:
    main_field:
      dataset: data
      when: '$iter<10'
      memory_selection:
        size:  ['$dsize[0]-2', '$dsize[1]-2']
        start: [1, 1]
      dataset_selection:
        size:  [1, '$dsize[0]-2', '$dsize[1]-2']
        start: [$iter, '($dsize[0]-2)*$pcoord[0]', '($dsize[1]-2)*$pcoord[1]']
```

New config:
```yml
decl_hdf5:
  file: data.h5
  root:
    group_1:
      data:
        type: array
        subtype: double
        size: [10, '$psize[0]*($dsize[0]-2)', '$psize[1]*($dsize[1]-2)']
      subgroup_1:
    group_2:
      subgroup_1:
      /group_1:
  write:
    main_field:
      dataset: /group_1/data  #full HDF5 path to dataset
      when: '$iter<10'   
      memory_selection:
        size:  ['$dsize[0]-2', '$dsize[1]-2']
        start: [1, 1]
      dataset_selection:
        size:  [1, '$dsize[0]-2', '$dsize[1]-2']
        start: [$iter, '($dsize[0]-2)*$pcoord[0]', '($dsize[1]-2)*$pcoord[1]']
```

As you can see groups are defined starting with `root` node.

`root` has 2 groups: `group_1` and `group_2`.

`group_1` has dataset `data` and group `subgroup_1`.

`group_2` has empty group `subgroup_1` (which is not related with `/group_1/subgroup_1`) and reference to `/group_1`. This reference is needed to support HDF5 groups cycles: [LINK](https://support.hdfgroup.org/HDF5/doc1.6/UG/09_Groups.html)

@jbigot What do you think about it? I don't want to change decl_HDF5 plugin without your permission.
