### ISSUE TITLE
Metadata type definition in data node

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#159]
In GitLab by @ksiero on Dec 6, 2019, 14:57

The idea is to join metadata type definition to data type definition and add special node that will indicate which of data PDI should make a copy when reclaiming the last reference.

From:
```yaml
metadata:
  array_size: int
data:
  some_array: {type: array, subtype: int, size: $array_size}
init_value:
  array_size: 3
  some_array: [0, 1, 2]
```

To:
```yaml
data:
  some_array: {type: array, subtype: int, size: $array_size}
  array_size: int
keep_copy:
  - array_size
init_value:
  array_size: 3
  some_array: [0, 1, 2]
```

Maybe there is a better name than `keep_copy`.
