### ISSUE TITLE
Array operators

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#160]
In GitLab by @ksiero on Dec 6, 2019, 15:29

There is an idea to add some array operators:
- size/len operator; example:

  ```yaml
  data:
    some_array: {type: array, subtype: int, size: 32}
    array_copy: {type: array, subtype: int, size: LEN(some_array)}
  ```

- dimension operator,
- shape operator.

I think there have more use cases inside the plugins configurations.
