### ISSUE TITLE
Relative reference-expressions support

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#266]
It would be nice to support relative expressions, for example to support the following C-type:
```
typedef struct {
  size_t size;
  double* data;
} myvector_t;
```

we would like to have something like:
```
type: record
buffersize: 16
members:
  size:
    disp: 0
    type: int64
  data:
    disp: 8
    type: pointer
    subtype:
      type: array
      subtype: double
      size: ${<self>.size}
```

this would mean that when we parse a type we introduce a new local context that forwards to global values when itself resolved.

All of this requires some thinking and the illustrative proposed syntax is in no way final of course
