### ISSUE TITLE
Data, metadata and plugins yaml value as a list

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#309]
In GitLab by @ksiero on Feb 11, 2021, 11:06

To support include mechanism, the `data`, `metadata` and `plugins` should be prepared to take also list of elements. This will allow to include more that one file in the same map. 

```yaml
data:
  - !include "data_sec1.yml"
  - !include "data_sec2.yml"
plugins:
  - !include "decl_hdf5.yml"
  - !include "decl_netcdf.yml"
```
