### ISSUE TITLE
Set_value plugin event and release feature

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#312]
In GitLab by @ksiero on Feb 16, 2021, 09:31

@youldrouis is missing calling event and release the data from `set_value` plugin.

The use case is to write `dimMax` using `decl_hdf5` plugin. PDI does not support plugin order event calls, so it has to be done in two events. After writing the data, it should be released.
```yml
plugins:
  set_value:                                                                                         
    on_event:                                                                                        
      f5D_global_values:                                                                             
        - share:                                                                                                          
          - dimMax: ['$rg[$Nr]', '$thetag[$Ntheta]', '$phig[$Nphi]', '$vparg[$Nvpar]', '$mug[$Nmu]' ]
        - event: "f5D_global_values_hdf5"
        - release: [dimMax]  
```
