### ISSUE TITLE
decl_hdf5: take the last element of the path as default data name

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#321]
In GitLab by @ksiero on Mar 1, 2021, 11:46

We support default data name as last element of the path in attributes:
If PDI data name is `attr_value` and path `/group1/group2/dest#attr_value` in `write` subtree, then in the HDF5 file it will be:

```yml
group1:
  group2:
    dset: #attr_value -> attrubute of dset
```

It would be nice to have the same for datasets. For example:
```yml
data:
  dset: ...
plugin:
  decl_hdf5:
    file: ...
    write: /group1/group2/dset # write dset data to group1/group2
```
