### ISSUE TITLE
Clear way to keep variables between different pycall events

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#323]
In GitLab by @cwitzler on Mar 4, 2021, 15:31

If I want to use a variable created in an init event, there is no clear way to pass this reference to another event.

For example:
```
pycall:
  on_event:
    init:
      global: { initValue }
      exec: |
        initValue= 3
    update:
      with: { initValue: $initValue }
      exec: |
        newValue = 2*initValue
```
