### ISSUE TITLE
FPE exceptions are thrown when enabled and values are passed to python

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#332]
As reported by Emilio J. Padrón on Slack (Thank you :pray: :heart: Emilio):

The following Fortran program:
```
program event
  use paraconf
  use pdi
  implicit none

  type(pc_tree_t),target :: conf
  integer                :: my_world

  call pc_parse_path("pycall_ondata.yml", conf)
  call pdi_init(conf)

  my_world = 42

  print *, "Fortran value: ", my_world

  call pdi_expose("world", my_world, pdi_out)

  call pdi_finalize()

end program event
```

with this PDI specification tree:
```
data:
  world: int

plugins:
  pycall:
    on_data:
      world: print(' Python value:', world)
```

compiled with `-ffpe-trap=invalid,zero,overflow` (overflow is the important one here)

Leads to a FPE exception.
