### ISSUE TITLE
Datatype attributes support

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#337]
In GitLab by @ksiero on Apr 30, 2021, 14:18

Some plugins would want to know more about types. For example in decl_netcdf the compound type has to have a name. This can be handled by providing attribute support for types. The attribute key will start with `+` sign, for example:
```yaml
types:
  inner_type:
    type: struct
    +decl_netcdf.object_path: "/types/inner_record"
    members: #...
data:
  my_data:
    type: struct
    +decl_netcdf.object_path: "/types/outer_record"
    members:
      inner_record:
         type: inner_type
plugins: ...
```
