### ISSUE TITLE
Data dependency yaml syntax

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#338]
In GitLab by @ksiero on Apr 30, 2021, 14:25

To allow data depend on some metadata we need to provide a syntax for it in yaml. After discussion on slack here is the first prototype:
```yml
metadata:
  timestep:
    type: struct
    members:
      id: int
      time: double
  global_rank: int
data:
  my_data:
    <depends_on>: { time: "$timestep.time", rank: "$global_rank" }
    type: struct
    members: #...
```

This would mean the time and rank will be also stored when `my_data` is shared.
