### ISSUE TITLE
Offer a view mechanism

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#342]
We should support a view system directly in PDI instead of re-implementing it in each and every plugin:

The syntax could be something like:
```yaml
data:
  gtemp: #< virtual global 3D array (t, x, y)
    type: array
    subtype: double
    size: [ inf, '$global_size[0]', '$global_size[1]' ]
  temp:
    type: array_view
    view_of: gtemp
    buffer_size: [ '$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]' ]
    buffer_selection_start: [ '$ghosts[0]', '$ghosts[1]' ]
    size: [ 1, '$local_size[0]', '$local_size[1]' ]
    start: [ $timestep, '$global_pos[0]', '$global_pos[1]' ]
```

**Comment by jbigot** [comment]
In GitLab by @ksiero on Aug 5, 2021, 10:36

Maybe this is more clear?

```yaml
data:
  gtemp: 
    type: array
    subtype: double
    size: [ inf, '$global_size[0]', '$global_size[1]' ]
    selection:
      temp:
        size: [1, '$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
        start: [$timestep, '$global_pos[0]', '$global_pos[1]']
  temp:
    type: array
    subtype: double
    size: ['$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]']
    selection:
      gtemp:
        size: ['$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
        start: ['$ghosts[0]', '$ghosts[1]']
```

**Comment by jbigot** [comment]
In GitLab by @ksiero on Aug 5, 2021, 14:18

After discussion with Amal we are divided by two ideas:

`map_in` mapping in the root, with named selections:
```yaml
data:
  global: # aka dataset
    type: array
    subtype: double
    size: [ inf, '$global_size[0]', '$global_size[1]' ]
  local: # data
    type: array
    subtype: double
    size: ['$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]']
map_in:
  map_1:
    local:
      size: ['$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
      start: ['$ghosts[0]', '$ghosts[1]']
    global:
      size: [1, '$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
      start: [$timestep, '($local_size_with_ghosts[0] - 2) * $rank_pos[0]', '($local_size_with_ghosts[0] - 2) * $rank_pos[1]']
plugins:
  decl_hdf5:
    file: data.h5
    write:
      local: # the name of the data to write
        dataset: global # the name of the data that describes the dataset
        selection: map_1
```

And `selection_for` as a type subtree, which works more like casting operator:
```yaml
data:
  global: # aka dataset
    type: array
    subtype: double
    size: [ inf, '$global_size[0]', '$global_size[1]' ]
    selection_for:
      local:
        size: [1, '$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
        start: [$timestep, '($local_size_with_ghosts[0] - 2) * $rank_pos[0]', '($local_size_with_ghosts[0] - 2) * $rank_pos[1]']
  local: # data
    type: array
    subtype: double
    size: ['$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]']
    selection_for:
      global:
        size: ['$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
        start: ['$ghosts[0]', '$ghosts[1]']
plugins:
  decl_hdf5:
    file: data.h5
    write:
      local: # the name of the data to write
        dataset: global # the name of the data that describes the dataset
```

**Comment by jbigot** [comment]
In GitLab by @agueroud on Aug 5, 2021, 19:05

For me the first one seems much more interesting:
having a `map_in` this way : give us the possibility to define multiple map_ins for the same data, this way i can use different map_ins for different plugins, or even in the same plugin (this is not possible when doing the map_in in the data subtree itself, unless you redefine the data every time you need another map_in :thinking_face: that's an interesting point in my opinion

**Comment by jbigot** [comment]
In GitLab by @ksiero on Aug 6, 2021, 09:05

Is it possible use-case, that the local data can have different map_ins into the global data (where both remain the same types)?

**Comment by jbigot** [comment]
In GitLab by @ksiero on Aug 6, 2021, 13:46

Here is next iteration of the ideas:
```yaml
data:
  global_r: # aka dataset
    type: struct
    members:
      position_member: &paricle_data
        type: array
        subtype: double
        size: [ inf, '$global_size[0]', '$global_size[1]' ]
      velocity_member: *paricle_data
      size: int
  local_p: # data
    type: array
    subtype: double
    size: ['$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]']
  local_v: # data
    type: array
    subtype: double
    size: ['$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]']
  data_size: int
  
map_in:
  - global_r.position_member:
      size: [1, '$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
      start: [$timestep, '($local_size_with_ghosts[0] - 2) * $rank_pos[0]', '($local_size_with_ghosts[0] - 2) * $rank_pos[1]']
    local_p:
      size: ['$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
      start: ['$ghosts[0]', '$ghosts[1]']
  - global_r.velocity_member:
      size: [1, '$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
      start: [$timestep, '($local_size_with_ghosts[0] - 2) * $rank_pos[0]', '($local_size_with_ghosts[0] - 2) * $rank_pos[1]']
    local_v:
      size: ['$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
      start: ['$ghosts[0]', '$ghosts[1]']
  - global_r.size: $size

plugins:
  decl_hdf5:
    file: data.h5
    write:
      local_v: # the name of the data to write
        dataset: global_r # the name of the data that describes the dataset
      local_p: # the name of the data to write
        dataset: global_r # the name of the data that describes the dataset
```
and:
```yaml
data:
  global_r: # aka dataset
    type: struct
    members:
      position_member: &paricle_data
        type: array
        subtype: double
        size: [ inf, '$global_size[0]', '$global_size[1]' ]
      velocity_member: *paricle_data
      size: int
    +selection_for:
      local_p:
        position_member: &position_member_selection_for
          size: [1, '$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
          start: [$timestep, '($local_size_with_ghosts[0] - 2) * $rank_pos[0]', '($local_size_with_ghosts[0] - 2) * $rank_pos[1]']
      local_v:
        velocity_member: *position_member_selection_for
      data_size: $size
  local_p: # data
    type: pointer
    subtype:
      type: array
      subtype: double
      size: ['$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]']
      +selection_for:
        global_r.position_member: &local_p_global_p_selection_for
          size: ['$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
          start: ['$ghosts[0]', '$ghosts[1]']
  local_v: # data
    type: array
    subtype: double
    size: ['$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]']
    +selection_for:
      global_r.velocity_member: *local_p_global_p_selection_for
  data_size: int
plugins:
  decl_hdf5:
    file: data.h5
    write:
      local_v: # the name of the data to write
        dataset: global_r # the name of the data that describes the dataset
      local_p: # the name of the data to write
        dataset: global_r # the name of the data that describes the dataset

```

**Comment by jbigot** [comment]
I like the map_in option too as it seems more flexible for use-cases we don't think of yet.
For the multiple map_in. One may think of a single buffer used for two different mappings depending on the time step... Not really a good idea, but possible

**Comment by jbigot** [comment]
In GitLab by @ksiero on Sep 9, 2021, 15:23

Last(?) iteration idea:
```yaml
data:
  local_p: # data
    type: array
    subtype: double
    size: ['$local_size_with_ghosts[0]', '$local_size_with_ghosts[1]']

views:  
  global_r: # aka dataset
    type: array_view
    subtype: double
    size: [*, '$global_size[0]', '$global_size[1]' ]
    mappings:
      - data:
          name: $local_p              
          size: ['$local_size_with_ghosts[0] - 2', '$local_size_with_ghosts[1] - 2']
          start: ['$ghosts[0]', '$ghosts[1]']
        dims_order: [, 0, 1]
        start: [$timestep, '($local_size_with_ghosts[0] - 2) * $rank_pos[0]', '($local_size_with_ghosts[0] - 2) * $rank_pos[1]'] #before changing dims order

plugins:
  decl_hdf5:
    file: data.h5
    on_event: event
    write: global_r # the name of the data that describes the dataset

```
