### ISSUE TITLE
Unable to use a $-ref to an array as size

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#372]
I would like to use the following data section in my use-case:
```
data:
  array_rank: int64
  array_size: { type: array, subtype: int64, size: '$array_rank' }
  array_data:
    type: array
    subtype: double
    size: '$array_size'
```

This does unfortunately fail with the following message:
```
[PDI] *** error: while referencing `array_size': Type_error: Expected scalar, found invalid type instead: type: array
dense: true
buffersize: 16
datasize: 16
alignment: 8
size: 2
start: 0
subsize: 2
subtype: 
        type: scalar
        kind: signed
        dense: true
        buffersize: 8
        datasize: 8
        alignment: 8
```
