### ISSUE TITLE
Support creation of new type templates

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#374]
It would be very useful to support creation of new type templates when creating complex types (typically a hierarchy of records and arrays) that appear many times in code with only some parameters (an array size for example) changing.

This could for example look as follow:
```
types:
  my_type:
    context:
      T: type
      S: integer
    type:
      type: array
      size: "${S}"
      subtype: T
data:
  d1:
    type: my_type
    S: 3
    T: int
```

To achieve that, we should follow an approach similar to `Expression`:
* the current `DatatypeTemplate` class should be renamed `DatatypeExpression`, *i.e.* something that can be evaluated to a datatype given a context,
* a new `DatatypeTemplate` class should be created that contains a `LocalContext` and a `DatatypeExpression`, this should behave like a function, *i.e.* the `LocalContext` acts as a `Context` providing local variables for the inner expression,
* a new `TemplateReference` that inherits from `Datatype` and references a `DatatypeTemplate` should be created, this should behave like a function, *i.e.* store values associated to the local variables of the `DatatypeTemplate` local variables,
* it should be possible to create instances of `DatatypeTemplate` from YAML just like it is possible to create instances of `Datatype`.

**Comment by jbigot** [comment]
In GitLab by @ksiero on Oct 4, 2021, 13:00

Shouldn't it be:
```yaml
data:
  d1:
    type: my_type
    S: 3
    T: int

```
