### ISSUE TITLE
Strange behavior of the subsize and start keywords in array datatype

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#382]
In GitLab by @agueroud on Nov 9, 2021, 16:06

I define my array this way in the yml file and I pass it to deisa plugin (python based plugin).
```
data:
    local_t:
      type: array
      subtype: double
      size: ['$dsize0', '$dsize1']
      subsize: ['$dsize0 - 2', '$dsize1 - 2']
      start: [1, 1]
```
When the `start : [0,0]` is set, the data values are correct. However I noticed strange values in the arrays I share when it is set to `start: [1, 1]`. It seems that the new pointer to the data is not well set.

I had a quick discussion with Karol, who suggested to try to serialize my data before passing it to deisa. It seems to solve my issue :)

Karol thinks that there is maybe a bug in the `to_python` function.
