### ISSUE TITLE
set_value plugin not working properly

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#429]
In GitLab by @Yushan-Wang on Sep 2, 2022, 15:22

What I want to achieve:
- define the value of variable `should_copy` in yaml
- get the value in C via `PDI_access`

Error I got:
- `Referencing null data with non-null size`

[io_root.yml](https://gitlab.maisondelasimulation.fr/pdidev/pdi/uploads/133ad23d65e36e1168850ed8dab3bfcb/io_root.yml)

**Comment by jbigot** [comment]
I tried with the following yaml and didn't get an error:
```
  metadata:
    my_value: int
  data:
  plugins:
    set_value:
      on_init:
        - expose:
          - my_value: 1
```
