### ISSUE TITLE
make kokkos_view a datatype

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#454]
In GitLab by @Yushan-Wang on Jul 12, 2024, 14:15

Idea from @tpadioleau 

In a kokkos-enabled code, we could pass the kokkosView pointer to PDI rather than the `.data()`

It will reduce a good amount of yaml configs where the size of these views are not provided by yaml. PDI will have information of the data size by querying the view's `extent` 

It can also be useful when PDI will have GPU support.

```
data:
    my_field: kokkos_view

plugin:
    decl_hdf5:
      ...
      write: my_field
```

**Comment by jbigot** [comment]
In GitLab by @tpadioleau on Jul 12, 2024, 18:08

That would be really cool

**Comment by jbigot** [comment]
Two ways we could do that:
1. with a dedicated kokkos plugin that would register the view type,
2. with better C++ support where we would declare a PDI type
```yaml
kokkos_view:
  type: serialized_struct
  content:
    data: [...]
    extents: [...]
```
then we could provide a function:
```c++
namespace pdi{
void share(std::string name, kokkos_view view, access a)
{
  PDI::event("start_serialized_struct(kokkos_view)");
  PDI::share("data", view.data(), a);
  PDI::share("extents" view.extents());
  PDI::event("end_serialized_struct");
}
}
```
