### ISSUE TITLE
Error in the Set_value plugin on macOS

### ISSUE THREAD

**Issue by tpadioleau** [pdidev/pdi#538]
During the Gysela week a macOS user encountered an error using the Set_value plugin
```
[PDI][NOINIT] *** Fatal error: Type_error: Referencing null data with non-null size
```

The part relative to this plugin in the YAML file was:
```yaml
metadata:
  iter : int
  iter_start : int
  nbstep_diag: int
  iter_saved : int

plugins:
  set_value:
    on_init:
      - share:
        - iter_saved: 0
    on_data:
      iter:
        - set:
          - iter_saved: '${iter_start} + ${iter}/${nbstep_diag}'
    on_finalize:
      - release: [iter_saved]
```

Using the same YAML file and C++ source code on linux does not trigger any warning/error.

@Yushan-Wang is already aware of this issue but I prefer that we keep track of it.
