### ISSUE TITLE
allow yaml data to be referred

### ISSUE THREAD

**Issue by Yushan-Wang** [pdidev/pdi#557]
in simulation codes:
`PDI_expose("fixed_data", ...)`

in yaml config:
```
data:
  fixed_data: ...
  tmp_data: $fixed_data
plugin:
  hdf5:
    write: $tmp_data
```
