### ISSUE TITLE
Update FTI in FTI plugin

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#81]
In GitLab by @jbigot on Mar 23, 2018, 12:01

**Comment by jbigot** [comment]
a few questions about your FTI plugin improvement:
* why a numbered map for `checkpoint` instead of a list
* how is `checkpoint` different from `snapshot` and `recover`?
* could you provide defaults or simplified versions for most options (Cf. Decl'HDF5)
* is there a way to not use the `init_on` event
* does `dataset` have to be the same for all situations, is there no way to change dataset

**Comment by jbigot** [comment]
In GitLab by @tpaluszk on Aug 7, 2018, 10:09

* why a numbered map for `checkpoint` instead of a list   
  With `FTI` it doesn't make sense to specify the same level of checkpoint multiple times as they would overwrite each other, so my idea here was to make this a map, and then check the values of keys if they are in the range 0-4 (probably better keys would be L1, L2, L3, L4 instead of 0-4) or if there are any duplicates.
* how is `checkpoint` different from `snapshot` and `recover`?  
  `snapshot` in `FTI` is a multi-use function, it basically does all the work for the user - when called, it checks if recovery is needed, if not checks whether it's time to perform a checkpoint based on the times specified in the `FTI` config file (can checkpoint on all levels from L1 to L4) but it's not possible for user to exactly tell when the checkpoint will occur. On the other hand `checkpoint` and `recover` are for more control over when the checkpoints are being done. `Checkpoint` performs a checkpoint the moment it is called, `recover` recovers the protected data when called.
* could you provide defaults or simplified versions for most options (Cf. Decl'HDF5)  
  Sorry, but I don't understand how is it different from the config I posted before. The simplest version would use `snapshot` only (the behavior of using them both - `snapshot` and `checkpoint` together is quite strange, probably not intended to be used together).   
So the simple version would be (without init event):
```yaml
    decl_fti:
      config_file: fti_config.ini
      communicator: $MPI_COMM_WORLD
      dataset:
        0: $main_field
        1: $iter
      snapshot_on: newiter
```

* is there a way to not use the `init_on` event  
  I mentioned that above. The other option is to initialize when both `config_file` (I had idea to handle the config file name the same way as the filenames in `decl'HDF5`) and `communicator` are accessible. I thought that init on event would be better because user would know exactly when he initializes `FTI`.
* does `dataset` have to be the same for all situations, is there no way to change dataset  
 There are currently no support for removing data from protected list, the only way to not save data is to change its size to 0 in that list.

**Comment by jbigot** [comment]
> With FTI it doesn't make sense to specify the same level of checkpoint multiple times as they would overwrite each other, so my idea here was to make this a map, and then check the values of keys if they are in the range 0-4 (probably better keys would be L1, L2, L3, L4 instead of 0-4) or if there are any duplicates.

Ok, I hadn't understood the numbers represented the checkpoint level

**Comment by jbigot** [comment]
I would however make sense to support checkpointing on multiple events just as you can call `FTI_Ckpt` in multiple places. Maybe your main loop iteration is very long and can be restarted either from the start of from the middle.

**Comment by jbigot** [comment]
In GitLab by @tpaluszk on Aug 8, 2018, 09:17

>  I would however make sense to support checkpointing on multiple events just as you can call `FTI_Ckpt` in multiple places. Maybe your main loop iteration is very long and can be restarted either from the start of from the middle.

I agree. We can support this by repeating checkpoint specification like this:
```yaml
 checkpoint:
        L1: { on_event: ckpt } # autoincrement if id not specified
        L1: { on_event: another_ckpt }
```
but in this solution user must be careful when using own checkpoint's ids (I'm not sure what is behavior of `FTI` when user tries to make a checkpoint with lower id).
Other option is to support lists in `on_event`:
```yaml
 checkpoint:
        L1: { on_event: [ckpt, another_ckpt] } # autoincrement if id not specified
```
The same can be done with `when`.

**Comment by jbigot** [comment]
the first option can not be used as you can not have repeated keys, the second one looks nice to me

**Comment by jbigot** [comment]
In GitLab by @tpaluszk on Aug 8, 2018, 10:02

Yea, right. I forgot about that.

**Comment by jbigot** [comment]
In GitLab by @tpaluszk on Aug 16, 2018, 11:56

With current implementation of `FTI` there is a problem with head processes from `FTI` and `mpi plugin`. These processes call `MPI_Finalize` inside `FTI` and after that exit, which means they destroy `mpi plugin` object, and this object has to free predefined communicators. This leads to calling a `MPI` function after `MPI_Finalize`.

**Comment by jbigot** [comment]
In GitLab by @tpaluszk on Aug 20, 2018, 14:39

After initial implementation of `FTI plugin`, I see that some features in the proposed config file are unnecessary or not possible to implement, list below.  
- `when` in checkpoints - it could be useful, but it would require to check the `Expression` only when a descriptors used in evaluated expression are being exposed. With current implementation it's impossible to check, which descriptors an `Expression` references,  
- `dataset` could be changed to a list, it being a map doesn't give the user any advantages and only requires to manage datasets' ids, which could be handled by `PDI`,
- the same goes with checkpoints' ids, imo letting user specifying checkpoint's id creates additional effort for the user and doesn't provide any usage.  

Also in the previous proposal I forgot about a way to get `FTI_Status`.

Updated version of configuration:
```yaml
data:
  fti_status: int
...

decl_fti:
  config_file: fti_config.ini
  communicator: $MPI_COMM_WORLD
  dataset:
    - main_field
    - iter
    - asd
  status: fti_status
  snapshot_on: newiter
  recover_on: recover
  checkpoint:
    L1_on: ckpt_l1
    L2_on: [ckpt_l2_1, ckpt_l2_2]
    L3_on: [ckpt_l3_1, ckpt_l3_2]
    L4_on: ckpt_l4
```

Please let me know what are your thoughts.  
I have also a question. Is there a reason why older version of `FTI` is used in `PDI`?
