### ISSUE TITLE
New definition of datatypes in config

### ISSUE THREAD

**Issue by jbigot** [pdidev/pdi#98]
In GitLab by @ksiero on Sep 18, 2018, 15:12

Which one is better?

The one we came up with on Slack:
```yaml
#scalar1
my_scalar1: char

#scalar2
my_scalar2:
  type: char

#array
my_array:
  type: array
  element_type: int
  size: 6

#record1
my_record1:
  type: record
  sizeof: $recordSize
  members:
    m1:
      disp: 0
      type: char
    m2:
      disp: $mid
      type: array
      element_type: int
      size: [2, 2]
      subsize: [1,2]
      start: [1, 0]
    m3: 
      disp: $mc2
      type: char

#record2
my_record2:
  type: C_record
  members:
    - m1: char
    - m2:
        type: array
        element_type: int
        size: 5
```

or 

```yaml
#scalar1
my_scalar1: char

#scalar2
my_scalar2:
  type: scalar
  datatype: char

#array
my_array:
  type: array
  datatype: int
  size: 6

#record1
my_record1:
  type: record
  sizeof: $recordSize
  members:
    m1:
      disp: 0
      type: scalar
      datatype: char
    m2:
      disp: $mid
      type: array
      datatype: int
      size: [2, 2]
      subsize: [1,2]
      start: [1, 0]
    m3:
      disp: $mc2
      type: scalar
      datatype: char

#record2
my_record:
  type: C_record
  members:
    - m1: char
    - m2: 
        type: array
        datatype: int
        size: 5
```

The main difference is that in the second option the `type` always means the same.

What do you think?

**Comment by jbigot** [comment]
In GitLab by @ksiero on Sep 18, 2018, 15:33

The second option would be also useful for #65.

**Comment by jbigot** [comment]
I'd say we can go for option1 for scalars with both `scalar1` & `scalar2` by saying that the following two defs are equivalent:
```YAML
val: char
val:
  type: char
```

*i.e.* type is the default key

and `char` is a shorthand for the following:
```YAML
val:
  type: scalar
  size: 1
  align: 1
  kind: int
```

Just as in C++ you would do
```C++
template<>
using mychar<> = myscalar<1,1,int>;
```
